out_words<- c("instagram","bundessansweb","font","one","two","url","https","doclang","theme","actutab","pagename","n","ajaxtrustedurl","null",
              "function","optanonwrapper","home","menu","navigation","conózcanos","publicación","publicado","conózcanos","facetoptions",
              "resultpage","currentpathisadmin","cookies","caché","aquí","encontrará","newsletter",
              "aseurl","scriptpath","ajaxpagestate","false","page","diciembre","agosto",
              "linkedin", "enero", "febrero", "junio","webpage", "id","thumbnailurl",
              "important","color", "present","rgb","abc","banner","blue","bottom","btn","button",
              "cffajaxurl","cfflinkhashtags","col","cyan","download", "red", "green", "rojo", "verde",
              "facebook","ffffff","fff","flex","font","fta", "gray","color","black",
              "return","html","display","uppercase","margin","line","helvetica","arial",
              "decoration","left","float", "height","size","none","white","contraseña",
              "titulotags","separatags","border","decoration","countstatic","facebookstatic",
              "twitterstatic","googleplusstatic","auto","center","border","mozilla","italic",
              "stretch","swap","truetype","windows","face","quattrocento","jqueryparams",
              "password","weight", "style","family", "inicio","justify", "content",
              "header","solid", "background", "top","main", "body", "contenfooter", "items",
              "grid","end","top","span", "align", "width","align","megamenu","parent",
              "max","animation","twitter","window","español", "english", "ico","fontsize",
	      "font-size", "textsize", "lettersize", "charactersize", "typographysize", "textscale", 
	      "letterdimension", "textdimension", "letterscale", "textproportions", "fontsizeattribute", 
              "typesize", "textdimensions", "letterdimensions", "scalefactor", "textscalefactor", "letterscaling", 
              "dimension", "characterdimension", "typesetting", "styling", "fontmeasurement", "sizeattribute", 
              "textstyling", "textformatting", "typography",
              "caption","orange","linear","gradient","rgba","vivid","attr", "footer","allowrestart", "and", "chat",
              "arrow", "backgrounds","div","youtube","your","wrapper","www","widgettitle",
              "website","visitantes","type", "shadow","search","scroll","right", "repeat",
              "radius","position", "portal","png","please", "padding", "overflow",
              "instagramlive",  "slide","this","text", "img","images", "box","close","container",
              "date","dateformat","default","emoji","pum","thickbox","yyyy","title","javascript","three","listitem",
              "bold","fonts","web","image","tuesday","wednesday","umwelt","nav","layout","tbody","item","webkit","bar","info",
              "logo","comment","jquery","rel","sep","breadcrumblist","typeof","isg","trackpageview","blockquote","pale",
              "click","searchform","fullwidth","kpcontent","pdf","checkboxes","faq","five","nowrap","purple","alignleft",
              "kpthumb","dddddd","infobox","kpfoot","thumbnail","bluish","jtwt","viet","htmlelement","lazysizes","parsedown",
              "posts","dadada", "grey", "fusion", "itemlistelement", "copyright", "alignright","jpg", "sixth", "anticlickjack",
              "var", "frontend", "name","tabs", "name", "blog", "sidebar", "iki", "moz", "icon", "format", "slidingbar",
              "sliders", "column", "columns", "widget", "post", "median", "svg","headline","targetid","language","namedurl",
              "label","contentlink","fill","TRUE","true","read","social","video","normal","inline","classicurl","opacity",
              "min","buzxwi","hover","islive", "index","media","vjs","localelang","cubic", "teaser",
              "static","unicode","spacing","noto","boxed","row","textarea","avada","author",
              "light","screen","complaint","contact","icons","tfoot","pagination","flexslider",
              "letter","serif","selector","shortcode","ticket","hidden","pink","prev","previus",
              "mobile","present","design","secondary","sticky","preset",
              "side","oda","sans","thead","sans","heading","chzn","cssgradients","boxes",
              "amber","drawn","socialmediaentry","slider","http","semibold","theantiquab",
              "droid","formatid","blush","staticurl","isintext","targetlanguage","legend",
              "welle","meta","scrollbar","ptx","abrava", "cent","irena","incl",
              "amcharts","they","abbreviation","abovementioned","activitieswithin",
              "actoin", "adadad", "alt", "appendix", "april", "areasmitigation",
              "abovementioned","fulfilment", "ies","january", "welcomeinfo",
              "twelve","welcome","tagline","arg","november","skip","wpfront", "open",
              "event", "tab", "istock", "per", "klimaschutzinitiative", "ts_inlinejs",
              "window.lazysizesconfig","_paq","matomo.php","createelement","s.parentnode.insertbefore",
              "cet","thursdays","pm","december","2023","sc","3den","0.43","__ref","_paq.push","setsiteid","d.getelementsbytagname",
              "d.createelement","2018","2016","2015","2017","g.org","this.src","window.projectsettings","footerlinkedcontent",
              "__typename","3fmaca","409p0","4cbqo","cursor","pointer","041","05b","041","05a","05b","060","061","07a","07a","07b","07e",
              "0a1","0a8","0a9","0aa","24f","24f","370","3ff","3ff","52f","5c666e", "range:u","sjjwi.in","002d5a","color:var",
              "__typename","maincontentimagelink","20and","20and","20and","20protecting","20biodiversity","20loss","20can","20we",
              "20civil","20rights","20go","20hand","20loss","3f","20planet","20go","20prevent","20biodiversity","20protecting",
              "20the","20rights","20and","20the","20planet","20we","20prevent","002d5a","0.91","62110756","footerlinkedsocialmediaaccount",
              "active:nth","020","0.40","1200px","clicking","ijabxv","lfyzoj","lhkjkz","lkmeix","lltjxc","sharingdescription","topicids",
              "topicschildren","topicsrelated","totalimages","totalpages", "twitteraccount","globalisierung","table","accommodating","willreadfrequently",
              "xls","xlsx","zip","bjdagw","notonaskharabic","notosansbengali","notosansdevanagari","notosansethiopic","contactform",
              "ellipsestext","rev","udffb","udfff","datemodified","datepublished","accordian","sp","placeholder","00",
              "255","300","2","wpcf7","form","240","3","ul","li","185","4","0px","1px","180","5","1px","165","145","ui","multiselect",
              "125","785510","120","shadow:inset","wp","108","116","6px","sorting_1","datatables_paginate","column.stripe",
              "column:first","table.datatable.order","sorting_3","td.dt","display:inline","li:nth","4px", "1.25em","button.default.button",
              "column:nth","src:local","1.25em","2em","transform:scale","1.5","5px","7px","8px","9px",
              "u003c","0.5s","datatables_wrapper","0.5","2s","e.canvas.width","214,173,90,0.8",
              "40","0.3","0.5em","table.datatable","th.dt","div.datatables_scrollbody","#000000", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF", 
              "#FFFF00", "#FF00FF", "#00FFFF", "#808080", "#800000", "#008000", "#000080", "#808000", "#800080", "#008080", "#C0C0C0", "#FFA500", "#800080", 
              "#A52A2A", "#FFD700", "#D2691E", "#8B4513", "#32CD32", "#008080", "#20B2AA", "#B22222", "#FF4500", "#8B0000", "#8B008B", "#483D8B", "#9400D3", 
              "#4B0082", "#800000", "#A52A2A", "#2E8B57", "#FF6347", "#FF7F50", "#6A5ACD", "#7B68EE", "#FF1493", "#8B008B", "#008B8B", "#8B4513", 
              "#FA8072", "#E9967A", "#00FA9A", "#9ACD32", "#556B2F", "#BDB76B", "#8B4513", "#DAA520", "#808000", "#2F4F4F", "#5F9EA0", "#4682B4", "#191970",
              "a.terminate","td.datatables_empty","styled.g102","na","nrc","unhcr","wvi","wa","ngos","ce","ip","esg","uk",
	      "iii","fgds","yep","set","ips","cpda","arra","maxwidth","const","sbti","pl","cdata","wmb","dolo","ado","tea","embu","kobe","due","nyeri","ahover",
              "styled.g101","styled.g103","styled.g104","styled.g105","styled.g106","fstatic","eoconst","async","ibid","etb","mt","prosopis","sbts","bbgcolumn","iftrue",
              "styled.g107","styled.g108","styled.g109","50","100","0.85","25","0.9","75","maxwidht",
              "maximumwidth", "maximalwidth", "maxwidth", "maximumsize", "limitwidth", "widthlimit", "maxdimensions", "maximaldimensions", "sizeconstraint", "maxextent", 
              "widthrestriction", "maximummeasurement", "maxspan", "maxbreadth", "maxmeasure", "maxlimitation", "widthboundary", "maximalextent", "maxspan", "maximumbreadth", 
              "breadthlimit", "sizelimit", "extentlimit", "maximalmeasure", "maximalbreadth", "maximalspan", "limitingwidth", "widththreshold", "maximumwidthvalue", "maximalsize", "maxvaluewidth",

              "c","n4","1","aa","s","ii","nthe","nand","nto","b","o","nin","co","e", "m","nof","nthis","nmately","fgd","gtmauth","disha","unment","dib","skao","eur",
              "nmental","nparis","t","mech", "nble","ps","showchar","subtitle","aligncenter","aexattr","fsready","kes","searchq","nfor","pydo","isinit","usedtget","usd",
              "email","imagetype","whatsapp","efefef","bfbfbf","infowindow","nth","0","1","2","3","4","5","6","7","8","9","fontweight","font weight","font-weight"
	      "slidingpopup","uhttps","linewidth", "columnwidth", "pagewidth", "characterwidth", "textsize", "fontwidth", "textlength", "textsize", "textformat", "textalignment",
              "HTML", "CSS", "JavaScript", "Python", "Ruby", "PHP", "Java", "C#", "ASP.NET", "Node.js", "React", "Angular", "Vue.js", "Django", "Flask", "Express.js", "Spring", 
	      "Bootstrap", "jQuery", "RESTful", "API", "JSON", "AJAX", "Git", "GitHub", "Heroku", "Responsive Design", "Front-end", "Back-end", "Full Stack", "Database", "SQL", "MongoDB", 
	      "Firebase", "Nginx", "Apache", "HTTP", "HTTPS", "Domain", "Hosting", "SSL", "CMS", "WordPress", "Jekyll", "SEO", "Web Security", "Cross-Origin", "Cookie", "Session", "OAuth", "JWT", "Websocket", "SPA", "MVC", "ORM", "CRUD",
	      "<!DOCTYPE>", "<html>", "<head>", "<title>", "<meta>", "<body>", "<header>", "<nav>", "<main>", "<section>", "<article>", "<aside>", "<footer>", "<h1>", "<h2>", "<h3>", "<h4>", 
              "<h5>", "<h6>", "<p>", "<a>", "<img>", "<div>", "<span>", "<ul>", "<ol>", "<li>", "<dl>", "<dt>", "<dd>", "<table>", "<tr>", "<td>", "<th>", "<form>", "<input>", "<textarea>", 
              "<select>", "<button>", "<label>", "<fieldset>", "<legend>", "<iframe>", "<audio>", "<video>", "<canvas>", "<script>", "<style>", "<link>", "<a href>", "<img src>", "<alt>", 
              "<href>", "<src>", "id", "class", "style", "width", "height", "padding", "margin", "border", "font-family", "color", "background-color", "text-align", "display", "position", 
              "float", "clear", "box-sizing", "overflow", "visibility", "z-index", "animation", "transition", "hover", "active", "focus", "before", "after",
              "I", "you", "he", "she", "it", "we", "they", "me", "you", "him", "her", "us", "them", "myself", "yourself", "himself", "herself", "itself", "ourselves", 
              "yourselves", "themselves", "mine", "yours", "his", "hers", "its", "our", "their", "oneself", "one","yo", "tú", 
              "él", "ella", "usted", "nosotros", "nosotras", "vosotros", "vosotras", "ellos", "ellas", 
              "ustedes", "mí", "ti", "él", "ella", "usted", "nosotros", "nosotras", "vosotros", "vosotras", 
              "ellos", "ellas", "ustedes", "me", "te", "le", "nos", "os", "les", "mío", "tuyo", "suyo", "nuestro", 
              "nuestra", "vuestro", "vuestra", "suyos", "suyas", "míos", "mías", "tuyos", "tuyas", "suyos", "suyas",
              "nuestros", "nuestras", "vuestros", "vuestras", "suyos", "suyas","aactive","aajeevika","aay","aayog",


"Ã„Â—nkÃƒÂ«mgezwat",
"Ã¢Â€Â¯lorawan",
"Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘Â‘Ã°ÂÂ‘Â’Ã°ÂÂ‘ÂÃ°ÂÂ‘Â¡",
"Ã°ÂÂ‘Â‘Ã°ÂÂ‘Â’Ã°ÂÂ‘ÂÃ°ÂÂ‘Â¡",
"Ã°ÂÂ‘Â‘Ã°ÂÂ‘Â¢Ã°ÂÂ‘ÂŸÃ°ÂÂ‘ÂŽÃ°ÂÂ‘ÂÃ°ÂÂ‘Â™Ã°ÂÂ‘Â’",
"Ã°ÂÂ‘Â‘Ã°ÂÂ‘Â¢Ã°ÂÂ‘ÂŸÃ°ÂÂ‘ÂŽÃ°ÂÂ‘ÂÃ°ÂÂ‘Â™Ã°ÂÂ‘Â’",
"Ã°ÂÂ‘Â’Ã°ÂÂ‘ÂžÃ°ÂÂ‘Â¢Ã°ÂÂ‘Â–Ã°ÂÂ‘Â£Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â™Ã°ÂÂ‘Â’Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘Â’Ã°ÂÂ‘ÂžÃ°ÂÂ‘Â¢Ã°ÂÂ‘Â–Ã°ÂÂ‘Â£Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â™Ã°ÂÂ‘Â’Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘Â“Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â‘",
"Ã°ÂÂ‘Â“Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â‘",
"Ã°ÂÂ‘Â“Ã°ÂÂ‘ÂŽÃ°ÂÂ‘ÂÃ°ÂÂ‘Â¡Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂŸ",
"Ã°ÂÂ‘Â“Ã°ÂÂ‘ÂŽÃ°ÂÂ‘ÂÃ°ÂÂ‘Â¡Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂŸ",
"Ã°ÂÂ‘Â‹",
"Ã°ÂÂ‘Â‹",
"Ã°ÂÂ‘Â›Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â›Ã°ÂÂ‘Â“Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â‘",
"Ã°ÂÂ‘Â›Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â›Ã°ÂÂ‘Â“Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â‘",
"Ã°ÂÂ‘Â£Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â™Ã°ÂÂ‘Â¢Ã°ÂÂ‘Â’",
"Ã°ÂÂ‘Â£Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â™Ã°ÂÂ‘Â¢Ã°ÂÂ‘Â’",
"Ã°ÂÂ‘Â‡",
"Ã°ÂÂ‘Â‡",
"Ã°ÂÂ‘Â‡i",
"Ã°ÂÂ‘Â‡i",
"Ã°ÂÂ‘Â‰",
"Ã°ÂÂ‘Â‰",
"Ã°ÂÂ‘ÂÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â›Ã°ÂÂ‘Â“Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â‘",
"Ã°ÂÂ‘ÂÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â›Ã°ÂÂ‘Â“Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â‘",
"Ã°ÂÂ‘Â–Ã°ÂÂ‘Â¡Ã°ÂÂ‘Â’Ã°ÂÂ‘Âš",
"Ã°ÂÂ‘Â–Ã°ÂÂ‘Â¡Ã°ÂÂ‘Â’Ã°ÂÂ‘Âš",
"Ã°ÂÂ‘Â–Ã°ÂÂ‘ÂšÃ°ÂÂ‘ÂÃ°ÂÂ‘Â™Ã°ÂÂ‘Â–Ã°ÂÂ‘ÂÃ°ÂÂ‘Â–Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘Â–Ã°ÂÂ‘ÂšÃ°ÂÂ‘ÂÃ°ÂÂ‘Â™Ã°ÂÂ‘Â–Ã°ÂÂ‘ÂÃ°ÂÂ‘Â–Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘ÂŒ",
"Ã°ÂÂ‘ÂŒ",
"Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â“",
"Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â“",
"Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂŸ",
"Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂŸ",
"Ã°ÂÂ‘ÂŒi",
"Ã°ÂÂ‘ÂŒi",
"Ã°ÂÂ‘ÂšÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â›Ã°ÂÂ‘Â¡Ã¢Â„ÂŽÃ°ÂÂ‘Â™Ã°ÂÂ‘Â¦",
"Ã°ÂÂ‘ÂšÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â›Ã°ÂÂ‘Â¡Ã¢Â„ÂŽÃ°ÂÂ‘Â™Ã°ÂÂ‘Â¦",
"Ã°ÂÂ‘ÂŸ",
"Ã°ÂÂ‘ÂŸ",
"Ã°ÂÂ‘ÂŸÃ°ÂÂ‘Â’Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘ÂŸÃ°ÂÂ‘Â’Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘ÂŸÃ°ÂÂ‘Â’Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¡Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â™",
"Ã°ÂÂ‘ÂŸÃ°ÂÂ‘Â’Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¡Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â™",
"Ã°ÂÂ‘ÂŸÃ°ÂÂ‘Â’Ã°ÂÂ‘ÂÃ°ÂÂ‘ÂŽÃ°ÂÂ‘Â¦Ã°ÂÂ‘ÂšÃ°ÂÂ‘Â’Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘ÂŸÃ°ÂÂ‘Â’Ã°ÂÂ‘ÂÃ°ÂÂ‘ÂŽÃ°ÂÂ‘Â¦Ã°ÂÂ‘ÂšÃ°ÂÂ‘Â’Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¡",
"Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â›Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¢Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â™Ã°ÂÂ‘Â–Ã°ÂÂ‘Â§Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â¡Ã°ÂÂ‘Â–Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â›",
"Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â›Ã°ÂÂ‘Â›Ã°ÂÂ‘Â¢Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â™Ã°ÂÂ‘Â–Ã°ÂÂ‘Â§Ã°ÂÂ‘ÂŽÃ°ÂÂ‘Â¡Ã°ÂÂ‘Â–Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â›",
"Ã°ÂÂ›Â¿",
"Ã°ÂÂ›Â¿",
"Ã°ÂÂ›Â¼",
"Ã°ÂÂ›Â¼",
"Ã°ÂÂ›Â½",
"Ã°ÂÂ›Â½",
"Ã°ÂÂ›Â½Ã°ÂÂ‘Â‡",
"Ã°ÂÂ›Â½Ã°ÂÂ‘Â‡",
"Ã°ÂÂÂ»Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â¢Ã°ÂÂ‘Â Ã°ÂÂ‘Â–Ã°ÂÂ‘Â›Ã°ÂÂ‘Â”",
"Ã°ÂÂÂ»Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â¢Ã°ÂÂ‘Â Ã°ÂÂ‘Â–Ã°ÂÂ‘Â›Ã°ÂÂ‘Â”",
"Ã°ÂÂÂ»Ã°ÂÂÂ»Ã°ÂÂ‘Â Ã°ÂÂ‘Â–Ã°ÂÂ‘Â§Ã°ÂÂ‘Â’",
"Ã°ÂÂÂ»Ã°ÂÂÂ»Ã°ÂÂ‘Â Ã°ÂÂ‘Â–Ã°ÂÂ‘Â§Ã°ÂÂ‘Â’",
"Ã°ÂÂÂ¶Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â›Ã°ÂÂ‘Â Ã°ÂÂÂ´Ã°ÂÂ‘Â”Ã°ÂÂ‘Â”",
"Ã°ÂÂÂ¶Ã°ÂÂ‘ÂœÃ°ÂÂ‘Â›Ã°ÂÂ‘Â Ã°ÂÂÂ´Ã°ÂÂ‘Â”Ã°ÂÂ‘Â”",
"Ã°ÂÂÂ·Ã°ÂÂ‘Â’Ã°ÂÂ‘ÂÃ°ÂÂ‘Â¡",
"Ã°ÂÂÂ·Ã°ÂÂ‘Â’Ã°ÂÂ‘ÂÃ°ÂÂ‘Â¡",
"Ã°ÂÂÂ·Ã°ÂÂ‘Â¢Ã°ÂÂ‘ÂŸÃ°ÂÂ‘ÂŽÃ°ÂÂ‘ÂÃ°ÂÂ‘Â™Ã°ÂÂ‘Â’Ã°ÂÂ‘Â ",
"Ã°ÂÂÂ·Ã°ÂÂ‘Â¢Ã°ÂÂ‘ÂŸÃ°ÂÂ‘ÂŽÃ°ÂÂ‘ÂÃ°ÂÂ‘Â™Ã°ÂÂ‘Â’Ã°ÂÂ‘Â ",
"Ã°ÂÂÂ¹Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â‘",
"Ã°ÂÂÂ¹Ã°ÂÂ‘ÂœÃ°ÂÂ‘ÂœÃ°ÂÂ‘Â‘",
"Ã°ÂÂœÂ€",
"Ã°ÂÂœÂ€",
"Ã°ÂÂœÂ‡",
"Ã°ÂÂœÂ‡",
"Ã°ÂÂœÂŽ",
"Ã°ÂÂœÂŽ",
"ÃÂƒc",
"ÃÂƒc",
"Ã 	",
"Ã 	",
"Ã 	",
"Ã 	",
"Ã 	",
"Ã 	",
"Ã¡lvarez",
"Ã¡lvarez",
"Ã¥ge",
"Ã¥ge",
"Ã¥sa",
"Ã¥sa",
"â€¯lorawan",
"Ã©galement",
"Ã©galement",
"Ã©nergie",
"Ã©nergie",
"Ã©valuation",
"Ã©valuation",
"Ã¶",
"Ã¶",
"Ã¼stÃ¼n",
"Ã¼stÃ¼n"


)


